### ISSUE TITLE
Need a master branch

### ISSUE THREAD

**Issue by ctam** [ucsf-education/tool_externaltaskmonitor#1]
I am getting this error message when I try to do a `git submodule update --remote`.  Most git commands expect 'master' branch to be there, so I recommend never delete the master branch but use it as a default branch for checking in new changes.

```
$ git submodule update --init --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'admin/tool/externaltaskmonitor'
```

**Comment by stopfstedt** [comment]
i've been trying to stay consistent with moodle's branch naming conventions, which is `MOODLE_XY_STABLE` and `MOODLE_XY_DEVEL`.

the current production branch is now `MOODLE_36_STABLE` and non-production is `MOODLE_36_DEVEL`. 

you can always use the `set-branch` command with `git submodule` to switch branches after the fact, or use the `-b <BRANCH>` option when adding the submodule via `git submodule add`. 
see https://git-scm.com/docs/git-submodule

**Comment by stopfstedt** [comment]
ok, per our converations - i've created a `master` branch that mirrors `MOODLE_36_STABLE` at this moment.
